import { Router } from "express";
import { randomUUID } from "crypto";
import { CartService } from "../services/carts.service.js";
import { ProductService } from "../services/products.service.js";

export const initRouter = Router();

const dataSet = [
  {
    title: "Croissant de Chocolate",
    description: "Delicioso croissant relleno de chocolate.",
    code: "Croissant-Chocolate",
    price: 2.99,
    status: true,
    stock: 50,
    category: "Panadería",
  },
  {
    title: "Tarta de Manzana",
    description: "Tarta clásica con capas de manzanas frescas y canela.",
    code: "Tarta-Manzana",
    price: 15.99,
    status: true,
    stock: 20,
    category: "Pastelería",
  },
  {
    title: "Eclair de Vainilla",
    description: "Eclair relleno de crema de vainilla y cubierto con glaseado.",
    code: "Eclair-Vainilla",
    price: 3.49,
    status: true,
    stock: 30,
    category: "Pastelería",
  },
  {
    title: "Baguette Tradicional",
    description: "Pan baguette crujiente con masa fermentada natural.",
    code: "Baguette-Tradicional",
    price: 4.99,
    status: true,
    stock: 40,
    category: "Panadería",
  },
  {
    title: "Tiramisú",
    description:
      "Postre italiano con capas de bizcocho, café y crema mascarpone.",
    code: "Tiramisu",
    price: 6.99,
    status: true,
    stock: 25,
    category: "Postres",
  },
  {
    title: "Cupcake de Fresa",
    description:
      "Cupcake esponjoso con frosting de fresa y decoración colorida.",
    code: "Cupcake-Fresa",
    price: 2.49,
    status: true,
    stock: 35,
    category: "Repostería",
  },
  {
    title: "Helado de Vainilla",
    description: "Helado clásico de vainilla con trozos de vaina de vainilla.",
    code: "Helado-Vainilla",
    price: 4.99,
    status: true,
    stock: 30,
    category: "Heladería",
  },
  {
    title: "Donut Glaseado",
    description: "Donut esponjoso cubierto con glaseado de azúcar.",
    code: "Donut-Glaseado",
    price: 1.99,
    status: true,
    stock: 45,
    category: "Repostería",
  },
  {
    title: "Cinnamon Roll",
    description: "Rollos de canela con glaseado de queso crema.",
    code: "Cinnamon-Roll",
    price: 3.99,
    status: true,
    stock: 25,
    category: "Panadería",
  },
  {
    title: "Muffin de Arándanos",
    description: "Muffin húmedo y esponjoso con arándanos frescos.",
    code: "Muffin-Arandanos",
    price: 2.79,
    status: true,
    stock: 40,
    category: "Repostería",
  },
  {
    title: "Gelato de Limón",
    description: "Helado italiano de limón con toques cítricos refrescantes.",
    code: "Gelato-Limon",
    price: 5.49,
    status: true,
    stock: 20,
    category: "Heladería",
  },
  {
    title: "Palmera de Chocolate",
    description: "Palmera hojaldrada con capas de chocolate crujiente.",
    code: "Palmera-Chocolate",
    price: 2.99,
    status: true,
    stock: 30,
    category: "Repostería",
  },
  {
    title: "Pastel de Zanahoria",
    description: "Pastel jugoso con zanahorias, nueces y crema de queso.",
    code: "Pastel-Zanahoria",
    price: 18.99,
    status: true,
    stock: 15,
    category: "Pastelería",
  },
  {
    title: "Panecillo Integral",
    description: "Panecillo integral con semillas de girasol y lino.",
    code: "Panecillo-Integral",
    price: 3.49,
    status: true,
    stock: 35,
    category: "Panadería",
  },
  {
    title: "Helado de Chocolate Amargo",
    description: "Helado intenso de chocolate amargo con trozos de cacao.",
    code: "Helado-Chocolate-Amargo",
    price: 5.99,
    status: true,
    stock: 25,
    category: "Heladería",
  },
  {
    title: "Cupcake de Vainilla",
    description:
      "Cupcake esponjoso con frosting de vainilla y decoración elegante.",
    code: "Cupcake-Vainilla",
    price: 2.49,
    status: true,
    stock: 30,
    category: "Repostería",
  },
  {
    title: "Brownie de Nuez",
    description: "Brownie denso y rico con trozos de nueces tostadas.",
    code: "Brownie-Nuez",
    price: 3.99,
    status: true,
    stock: 20,
    category: "Repostería",
  },
  {
    title: "Galletas de Avena y Pasas",
    description: "Galletas saludables con avena, pasas y un toque de canela.",
    code: "Galletas-Avena-Pasas",
    price: 1.99,
    status: true,
    stock: 40,
    category: "Repostería",
  },
  {
    title: "Rollito de Canela",
    description: "Rollito dulce con canela y glaseado de azúcar.",
    code: "Rollito-Canela",
    price: 2.99,
    status: true,
    stock: 25,
    category: "Panadería",
  },
  {
    title: "Mousse de Frambuesa",
    description: "Postre ligero y aireado con capas de mousse de frambuesa.",
    code: "Mousse-Frambuesa",
    price: 4.49,
    status: true,
    stock: 15,
    category: "Postres",
  },
  {
    title: "Pretzel de Caramelo",
    description: "Pretzel suave cubierto con caramelo y espolvoreado con sal.",
    code: "Pretzel-Caramelo",
    price: 2.79,
    status: true,
    stock: 30,
    category: "Repostería",
  },
  {
    title: "Helado de Fresa",
    description: "Helado cremoso de fresa con trozos de fruta fresca.",
    code: "Helado-Fresa",
    price: 4.99,
    status: true,
    stock: 25,
    category: "Heladería",
  },
  {
    title: "Tartaleta de Limón",
    description: "Tartaleta individual con relleno de crema de limón.",
    code: "Tartaleta-Limon",
    price: 3.49,
    status: true,
    stock: 25,
    category: "Postres",
  },
  {
    title: "Pan Multicereal",
    description: "Pan con mezcla de cereales como avena, linaza y girasol.",
    code: "Pan-Multicereal",
    price: 4.49,
    status: true,
    stock: 35,
    category: "Panadería",
  },
  {
    title: "Cupcake de Chocolate",
    description: "Cupcake esponjoso con frosting de chocolate y virutas.",
    code: "Cupcake-Chocolate",
    price: 2.49,
    status: true,
    stock: 30,
    category: "Repostería",
  },
  {
    title: "Gelato de Frutas del Bosque",
    description: "Helado italiano con mezcla de frutas del bosque frescas.",
    code: "Gelato-Frutas-Bosque",
    price: 5.49,
    status: true,
    stock: 20,
    category: "Heladería",
  },
  {
    title: "Bollo de Canela",
    description: "Bollo dulce con canela y glaseado de queso crema.",
    code: "Bollo-Canela",
    price: 2.99,
    status: true,
    stock: 25,
    category: "Repostería",
  },
  {
    title: "Profiteroles de Chocolate",
    description: "Pequeños bollos rellenos de crema y bañados en chocolate.",
    code: "Profiteroles-Chocolate",
    price: 4.99,
    status: true,
    stock: 15,
    category: "Repostería",
  },
  {
    title: "Helado de Menta con Chispas de Chocolate",
    description: "Helado refrescante con sabor a menta y trozos de chocolate.",
    code: "Helado-Menta-Chocolate",
    price: 5.99,
    status: true,
    stock: 20,
    category: "Heladería",
  },
  {
    title: "Palmera de Frambuesa",
    description: "Palmera hojaldrada con relleno de frambuesa y glaseado.",
    code: "Palmera-Frambuesa",
    price: 3.49,
    status: true,
    stock: 25,
    category: "Repostería",
  },
  {
    title: "Pastel de Chocolate Triple",
    description: "Pastel decadente con tres capas de chocolate y ganache.",
    code: "Pastel-Chocolate-Triple",
    price: 21.99,
    status: true,
    stock: 10,
    category: "Pastelería",
  },
  {
    title: "Rosquillas de Azúcar",
    description: "Rosquillas esponjosas cubiertas con azúcar glas.",
    code: "Rosquillas-Azucar",
    price: 2.49,
    status: true,
    stock: 30,
    category: "Repostería",
  },
  {
    title: "Cheesecake de Frutos Rojos",
    description: "Pastel de queso con una mezcla irresistible de frutos rojos.",
    code: "Cheesecake-Frutos-Rojos",
    price: 19.99,
    status: true,
    stock: 18,
    category: "Postres",
  },
  {
    title: "Crepes de Nutella y Plátano",
    description: "Crepes finos rellenos de Nutella y rodajas de plátano.",
    code: "Crepes-Nutella-Platano",
    price: 8.99,
    status: true,
    stock: 22,
    category: "Repostería",
  },
  {
    title: "Helado de Avellana Caramelizada",
    description:
      "Helado suave con avellanas caramelizadas y swirls de caramelo.",
    code: "Helado-Avellana-Caramelizada",
    price: 6.49,
    status: true,
    stock: 15,
    category: "Heladería",
  },
  {
    title: "Cupcake Red Velvet",
    description:
      "Cupcake esponjoso con sabor aterciopelado y frosting de queso crema.",
    code: "Cupcake-Red-Velvet",
    price: 3.29,
    status: true,
    stock: 28,
    category: "Repostería",
  },
  {
    title: "Tartaleta de Mango y Coco",
    description: "Tartaleta con relleno de mango fresco y coco rallado.",
    code: "Tartaleta-Mango-Coco",
    price: 4.99,
    status: true,
    stock: 20,
    category: "Postres",
  },
  {
    title: "Mousse de Chocolate Blanco",
    description: "Postre ligero con suave mousse de chocolate blanco.",
    code: "Mousse-Chocolate-Blanco",
    price: 5.49,
    status: true,
    stock: 25,
    category: "Postres",
  },
  {
    title: "Donut de Matcha",
    description:
      "Donut esponjoso con glaseado de té matcha y decoración de pistachos.",
    code: "Donut-Matcha",
    price: 2.79,
    status: true,
    stock: 30,
    category: "Repostería",
  },
  {
    title: "Pastel de Piña Colada",
    description: "Pastel tropical con piña, coco y un toque de ron.",
    code: "Pastel-Pina-Colada",
    price: 22.99,
    status: true,
    stock: 12,
    category: "Pastelería",
  },
  {
    title: "Profiteroles de Café",
    description:
      "Bollos rellenos de crema de café y cubiertos con glaseado de café.",
    code: "Profiteroles-Cafe",
    price: 4.99,
    status: true,
    stock: 18,
    category: "Repostería",
  },
  {
    title: "Gelato de Pistacho",
    description:
      "Helado italiano con sabor intenso a pistacho y trozos de nuez.",
    code: "Gelato-Pistacho",
    price: 5.99,
    status: true,
    stock: 20,
    category: "Heladería",
  },
  {
    title: "Cronut de Caramelo",
    description: "Fusión entre croissant y donut con relleno de caramelo.",
    code: "Cronut-Caramelo",
    price: 3.29,
    status: true,
    stock: 25,
    category: "Repostería",
  },
  {
    title: "Tarta de Durazno y Almendra",
    description: "Tarta delicada con duraznos frescos y almendras tostadas.",
    code: "Tarta-Durazno-Almendra",
    price: 17.99,
    status: true,
    stock: 15,
    category: "Pastelería",
  },
  {
    title: "Éclair de Pistacho",
    description: "Éclair relleno de crema de pistacho y glaseado de pistacho.",
    code: "Eclair-Pistacho",
    price: 4.49,
    status: true,
    stock: 30,
    category: "Pastelería",
  },
  {
    title: "Bagel Integral con Salmón",
    description: "Bagel integral con salmón ahumado, queso crema y eneldo.",
    code: "Bagel-Integral-Salmon",
    price: 6.99,
    status: true,
    stock: 20,
    category: "Panadería",
  },
  {
    title: "Helado de Mocaccino",
    description: "Helado con sabor a café y chocolate con trozos de almendra.",
    code: "Helado-Mocaccino",
    price: 5.79,
    status: true,
    stock: 22,
    category: "Heladería",
  },
  {
    title: "Doughnut de Lavanda",
    description: "Doughnut suave con glaseado de lavanda y pistachos picados.",
    code: "Doughnut-Lavanda",
    price: 2.99,
    status: true,
    stock: 28,
    category: "Repostería",
  },
  {
    title: "Cupcake de Maracuyá",
    description:
      "Cupcake esponjoso con frosting de maracuyá y decoración tropical.",
    code: "Cupcake-Maracuya",
    price: 3.49,
    status: true,
    stock: 25,
    category: "Repostería",
  },
  {
    title: "Galette de Fresas",
    description: "Galette rústica con fresas frescas y crema de almendra.",
    code: "Galette-Fresas",
    price: 9.99,
    status: true,
    stock: 18,
    category: "Pastelería",
  },
  {
    title: "Tarta de Queso con Cerezas",
    description: "Tarta de queso cremosa con topping de cerezas frescas.",
    code: "Tarta-Queso-Cerezas",
    price: 21.49,
    status: true,
    stock: 12,
    category: "Postres",
  },
  {
    title: "Helado de Coco Tostado",
    description:
      "Helado cremoso con coco tostado y virutas de chocolate blanco.",
    code: "Helado-Coco-Tostado",
    price: 6.49,
    status: true,
    stock: 20,
    category: "Heladería",
  },
  {
    title: "Limónada de Fresa Refrescante",
    description: "Limonada fresca con puré de fresa y hielo picado.",
    code: "Bebida-Limonada-Fresa",
    price: 3.99,
    status: true,
    stock: 50,
    category: "Bebidas",
  },
  {
    title: "Smoothie Tropical de Mango y Piña",
    description: "Mezcla suave de mango, piña, plátano y yogur.",
    code: "Bebida-Smoothie-Tropical",
    price: 4.49,
    status: true,
    stock: 40,
    category: "Bebidas",
  },
  {
    title: "Agua de Coco con Hierbabuena",
    description: "Agua de coco natural con hojas de hierbabuena.",
    code: "Bebida-Agua-Coco-Hierbabuena",
    price: 2.99,
    status: true,
    stock: 60,
    category: "Bebidas",
  },
  {
    title: "Frappé de Vainilla y Caramelo",
    description:
      "Mezcla helada de café con aroma de vainilla y jarabe de caramelo.",
    code: "Bebida-Frappe-Vainilla-Caramelo",
    price: 5.49,
    status: true,
    stock: 30,
    category: "Bebidas",
  },
  {
    title: "Té Helado de Frutas del Bosque",
    description: "Té negro helado con mezcla de frutas del bosque y hielo.",
    code: "Bebida-Te-Helado-Frutas-Bosque",
    price: 3.79,
    status: true,
    stock: 45,
    category: "Bebidas",
  },
  {
    title: "Cóctel de Maracuyá y Mango",
    description: "Cóctel refrescante con pulpa de maracuyá, mango y hielo.",
    code: "Bebida-Coctel-Maracuya-Mango",
    price: 7.99,
    status: true,
    stock: 25,
    category: "Bebidas",
  },
  {
    title: "Batido de Chocolate y Avellanas",
    description:
      "Batido cremoso con chocolate, avellanas y helado de vainilla.",
    code: "Bebida-Batido-Chocolate-Avellanas",
    price: 6.49,
    status: true,
    stock: 35,
    category: "Bebidas",
  },
  {
    title: "Zumo de Naranja Natural",
    description: "Zumo fresco exprimido de naranjas recién recolectadas.",
    code: "Bebida-Zumo-Naranja-Natural",
    price: 2.49,
    status: true,
    stock: 50,
    category: "Bebidas",
  },
  {
    title: "Café Helado con Almendras",
    description: "Café fuerte con hielo y leche de almendras.",
    code: "Bebida-Cafe-Helado-Almendras",
    price: 4.99,
    status: true,
    stock: 30,
    category: "Bebidas",
  },
  {
    title: "Lassi de Mango y Cardamomo",
    description: "Bebida hindú con yogur, mango y un toque de cardamomo.",
    code: "Bebida-Lassi-Mango-Cardamomo",
    price: 3.99,
    status: true,
    stock: 40,
    category: "Bebidas",
  },
];

initRouter.get("/", async (req, res) => {
  try {
    // Elimina todos los documentos de las colecciones
    await CartService.deleteMany();
    await ProductService.deleteMany();

    // Itera sobre el dataSet e inserta cada documento por separado
    for (const data of dataSet) {
      // Genera un nuevo ID aleatorio utilizando crypto
      data._id = randomUUID();

      // Inserta el documento en la base de datos
      await ProductService.createProduct(data);
      console.log("Documento insertado:", data.title);
    }

    res.send("Base de datos creada");
  } catch (error) {
    console.error(
      "Error durante la inicialización de la base de datos:",
      error
    );
    res.status(500).send("Error durante la inicialización de la base de datos");
  }
});
